name       : libzip
version    : 1.8.0
release    : 13
source     :
    - https://libzip.org/download/libzip-1.8.0.tar.xz : f0763bda24ba947e80430be787c4b068d8b6aa6027a26a19923f0acfa3dac97e
license    : BSD-3-Clause
component  : programming.library
summary    : libzip is a C library for reading, creating, and modifying zip archives
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - bzip2-devel
setup      : |
    %cmake . -DDOCUMENTATION_FORMAT=man
build      : |
    %make
install    : |
    %make_install
    # These files basically breaks cmake checks.
    rm -rf $installdir/%libdir%/cmake
check      : |
    %make check || :
