name       : libzip
version    : 1.3.0
release    : 5
source     :
    - https://nih.at/libzip/libzip-1.3.0.tar.xz : aa936efe34911be7acac2ab07fb5c8efa53ed9bb4d44ad1fe8bff19630e0d373
license    : BSD
component  : programming
summary    : libzip is a C library for reading, creating, and modifying zip archives.
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - bzip2-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/%libdir%/libzip/include/zipconf.h $installdir/usr/include/
    rm -rf $installdir/%libdir%/libzip
check      : |
    %make check
