name       : libzip
version    : 1.9.2
release    : 17
source     :
    - https://libzip.org/download/libzip-1.9.2.tar.xz : c93e9852b7b2dc931197831438fee5295976ee0ba24f8524a8907be5c2ba5937
license    : BSD-3-Clause
component  : programming.library
summary    : libzip is a C library for reading, creating, and modifying zip archives
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
mancompress: yes
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - bzip2-devel
setup      : |
    %cmake . -DDOCUMENTATION_FORMAT=man
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
