name       : libzip
version    : 1.5.1
release    : 10
source     :
    - https://github.com/nih-at/libzip/archive/rel-1-5-1.tar.gz : 3ca79ff6b9a02b3e3bcf0b45f30a8159c3146658f57c8b6be0a370eabd3db071
license    : BSD-3-Clause
component  : programming.library
summary    : libzip is a C library for reading, creating, and modifying zip archives
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - bzip2-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
