name       : libzip
version    : 1.7.1
release    : 11
source     :
    - https://github.com/nih-at/libzip/releases/download/v1.7.1/libzip-1.7.1.tar.xz : a020dc1b17a79faa748e43a05f8605d65e403813e8e97ad3a300a90ddba097ac
license    : BSD-3-Clause
component  : programming.library
summary    : libzip is a C library for reading, creating, and modifying zip archives
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - pkgconfig(liblzma)
    - bzip2-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    # These files basically breaks cmake checks.
    rm -rf $installdir/%libdir%/cmake
check      : |
    %make check || :
