name       : libzip
version    : 1.3.2
release    : 7
source     :
    - https://nih.at/libzip/libzip-1.3.2.tar.xz : 6277845010dbc20e281a77e637c97765c1323d67df4d456fd942f525ea86e185
license    : BSD-3-Clause
component  : programming
summary    : libzip is a C library for reading, creating, and modifying zip archives.
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - bzip2-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
