name       : libzip
version    : 1.5.0
release    : 8
source     :
    - https://nih.at/libzip/libzip-1.5.0.tar.xz : 5ddb9b41d31b2f99ad4d512003c610ae2db70e222833aba6f9332d5b48a153d9
license    : BSD-3-Clause
component  : programming
summary    : libzip is a C library for reading, creating, and modifying zip archives
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - bzip2-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
