name       : libzip
version    : 1.1.3
release    : 4
source     :
    - http://www.nih.at/libzip/libzip-1.1.3.tar.xz : 729a295a59a9fd6e5b9fe9fd291d36ae391a9d2be0b0824510a214cfaa05ceee
license    : BSD
component  : programming
summary    : libzip is a C library for reading, creating, and modifying zip archives.
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - pkgconfig(zlib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/%libdir%/libzip/include/zipconf.h $installdir/usr/include/
    rm -rf $installdir/%libdir%/libzip
