name       : libzip
version    : 1.1.2
release    : 3
source     :
    - http://www.nih.at/libzip/libzip-1.1.2.tar.xz : a921b45b5d840e998ff2544197eba4c3593dccb8ad0ee938630c2227c2c59fb3
license    : BSD
component  : programming
summary    : libzip is a C library for reading, creating, and modifying zip archives.
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - pkgconfig(zlib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
