name       : libzip
version    : 1.5.1
release    : 9
source     :
    - https://nih.at/libzip/libzip-1.5.1.tar.xz : 04ea35b6956c7b3453f1ed3f3fe40e3ddae1f43931089124579e8384e79ed372
license    : BSD-3-Clause
component  : programming
summary    : libzip is a C library for reading, creating, and modifying zip archives
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
builddeps  :
    - bzip2-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
